/**
 * @file font.h
 * @brief Bitmap fonts (generated by tools/make_font.py from BDF pixel fonts).
 *
 * See tools/make_font.py for the binary format. Fonts are stored in ROM and
 * read in place.
 */
#ifndef GFX_FONT_H
#define GFX_FONT_H

#include <stdint.h>

/** A font in the "OFNT" format. */
typedef struct {
    const uint8_t *data;
} font_t;

/** One glyph record. */
typedef struct {
    const uint8_t *bitmap; /**< 4 bits per pixel, rows padded to bytes. */
    uint8_t width;
    uint8_t height;
    int8_t x_offset;
    int8_t y_offset;
    uint8_t advance;
} glyph_t;

/** @brief Line height in pixels. */
int font_line_height(const font_t *font);

/** @brief Distance from the top of a line to the baseline. */
int font_ascent(const font_t *font);

/**
 * @brief Look up the glyph for @p c. Characters the font lacks (including
 * all non-ASCII bytes) are shown as '?'.
 */
void font_glyph(const font_t *font, unsigned char c, glyph_t *out);

/** The three fonts of the user interface. */
extern const font_t FONT_BODY;  /**< List rows and normal text (Galmuri11). */
extern const font_t FONT_SMALL; /**< Secondary text and button hints (Galmuri9). */
extern const font_t FONT_TITLE; /**< Title bar and headings (Galmuri11 Bold). */

#endif /* GFX_FONT_H */
