/**
 * @file font.h
 * @brief Bitmap fonts (generated by tools/make_font.py from BDF pixel fonts).
 *
 * See tools/make_font.py for the binary format. Fonts are stored in ROM and
 * read in place.
 */
#ifndef GFX_FONT_H
#define GFX_FONT_H

#include <stdint.h>

/** A font in the "OFN3" format. */
typedef struct font {
    const uint8_t *data;
    const struct font *fallback; /**< Asked for characters this font lacks, or NULL. */
} font_t;

/** One glyph record. */
typedef struct {
    const uint8_t *bitmap; /**< 1 bit per pixel, MSB first, rows padded to bytes. */
    uint8_t width;
    uint8_t height;
    int8_t x_offset;
    int8_t y_offset;
    uint8_t advance;
} glyph_t;

/** @brief Line height in pixels. */
int font_line_height(const font_t *font);

/** @brief Distance from the top of a line to the baseline. */
int font_ascent(const font_t *font);

/**
 * @brief Look up the glyph for Unicode code point @p c. Characters the font
 * lacks are taken from its fallback font, or else shown as '?'.
 */
void font_glyph(const font_t *font, uint32_t c, glyph_t *out);

/** The three fonts of the user interface. */
extern const font_t FONT_BODY;  /**< List rows and normal text (Galmuri11). */
extern const font_t FONT_SMALL; /**< Secondary text and button hints (Galmuri9). */
extern const font_t
    FONT_TITLE; /**< Title bar and headings (Galmuri11 Bold; kanji from FONT_BODY). */

#endif /* GFX_FONT_H */
